//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYDrmb.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreSetting
    {
        public int Id { get; set; }
        public string SettingId { get; set; }
        public string SettingValue { get; set; }
        public bool CanEdit { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public string updatedBy { get; set; }
    }
}
