//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYDrmb.Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HYDrmbEntities : DbContext
    {
        public HYDrmbEntities()
            : base("name=HYDrmbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoreSetting> CoreSettings { get; set; }
        public virtual DbSet<CoreUser> CoreUsers { get; set; }
        public virtual DbSet<RmbInOccupied> RmbInOccupieds { get; set; }
        public virtual DbSet<RmbReservation> RmbReservations { get; set; }
        public virtual DbSet<RmbReservedItem> RmbReservedItems { get; set; }
        public virtual DbSet<RmbResource> RmbResources { get; set; }
        public virtual DbSet<RmbRoom> RmbRooms { get; set; }
        public virtual DbSet<rmbReservation_view> rmbReservation_view { get; set; }
        public virtual DbSet<CoreHoliday> CoreHolidays { get; set; }
    }
}
