//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYDrmb.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RmbReservedItem
    {
        public int Id { get; set; }
        public string ResourceType { get; set; }
        public int ReservedObjectId { get; set; }
        public int ReservationId { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public string udpatedBy { get; set; }
    
        public virtual RmbReservation RmbReservation { get; set; }
    }
}
