//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYDrmb.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RmbReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RmbReservation()
        {
            this.RmbReservedItems = new HashSet<RmbReservedItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime ReservedStartAt { get; set; }
        public System.DateTime ReservedEndAt { get; set; }
        public string SessionType { get; set; }
        public string ContactName { get; set; }
        public string ContactPost { get; set; }
        public string ContactNumber { get; set; }
        public bool Invalid { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> ReservedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RmbReservedItem> RmbReservedItems { get; set; }
    }
}
