//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYDrmb.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class rmbReservation_view
    {
        public int Id { get; set; }
        public System.DateTime ReservedStartAt { get; set; }
        public System.DateTime ReservedEndAt { get; set; }
        public Nullable<System.DateTime> ReservedDate { get; set; }
        public string SessionType { get; set; }
        public string ContactName { get; set; }
        public string ContactPost { get; set; }
        public string ContactNumber { get; set; }
        public string RoomName { get; set; }
        public string RoomLocation { get; set; }
        public string FromTime { get; set; }
        public string TillTime { get; set; }
        public string LocationType { get; set; }
        public string RoomType { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> RoomObjectId { get; set; }
    }
}
