//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYDtmn.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class bkdDriver_view
    {
        public int Id { get; set; }
        public int Tag { get; set; }
        public int ReplacementId { get; set; }
        public bool IsTemporary { get; set; }
        public Nullable<System.DateTime> SubstitutedOn { get; set; }
        public Nullable<System.DateTime> ServicingFrom { get; set; }
        public bool IsCurrent { get; set; }
        public string DriverMobile { get; set; }
        public string DriverName { get; set; }
        public string PlateNo { get; set; }
        public string Preference { get; set; }
        public string NullaPreference { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public string updatedBy { get; set; }
        public bool Adhoc { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public int Priority { get; set; }
    }
}
