mindmap
    M1(Drivers - perm)
        D1(("
        ..
        Driver A"))
        ::icon(fa fa-id-card)
            T1))13/6/2024 valid((
            ::icon(fa fa-calendar)
            T2))21/6/2024 replace Driver B((
            ::icon(fa fa-calendar)
        D2(("
        ..
        Driver B"))
        ::icon(fa fa-id-card)
            T2))13/6/2024 valid((
            ::icon(fa fa-calendar)
            B1["Book at 21/6/2024"]
                AA1{{add book count for full}}
                A1{{add full on 21/6/2024 priority-B}}
            H1)Need Holiday(
                A2))replaced by Driver A((
                    A3))create duty on 21/6/2024 with Driver A((
                A4))change full on 21/6/2024 with priority-B((
                    S1{{set onleave = Driver B}}
                    S2{{set non-shared}}
                    A5))clear full count on 21/6/2024 with priority-B((
                A6))add full on 21/6/2024 shared priority-A((
                    AA6{{add back full count from priority-B}}